### ISSUE TITLE
Function not work

### ISSUE THREAD

**Issue by GabBiswajit** [alvin0319/CustomItemLoader#127]
**mining_speed: 20** Is Not Work At Pm4 Last Version

**Comment by alvin0319** [comment]
The `mining_speed` property didn't work when it was introduced and is already fixed in the PM5 ([commit](https://github.com/alvin0319/CustomItemLoader/pull/116/commits/9cdaf21a3cd8e54d0909d9fcdad8b1ce07f1c24c#diff-13eabe0cc062fcb511efa9f84fd907ca2bcdb45b1c89a9a8c820f530d0282dbb)) version. I have no plan to backport it for PM4, use PM5. PM4 will be abandoned anyway.
